### ISSUE TITLE
Add definition of snowball samling to TG

### ISSUE THREAD

**Issue by rkrug** [IPBES-Data/IPBES_TG_Snowballing#2]
Requested by MEP 13 Dec 2023.

Snowball sampling (also known as chain referral sampling) is defined as ...

**Comment by rkrug** [comment]
I suggest the following wording:

> Snowball sampling (also known as chain sampling, chain-referral sampling, referral sampling) is in the context of literature search a search which starts at some key-papers and adds the papers which are referenced in the key-papers as well as the papers citing one or more key-papers to the corpus of identified papers.

to replace the existing first sentence:

> Snowballing in literature search and analysis refers to the approach to search for literature starting from a set of identified key-papers.

**Comment by niamir** [comment]
reads great

**Comment by rkrug** [comment]
Fixed in https://github.com/IPBES-Data/IPBES_TG_Snowballing/commit/2771679090c6582aa8ff8a05654dae65070cb826 and released as [v0.5.1](https://github.com/IPBES-Data/IPBES_TG_Snowballing/releases/tag/v0.5.1)
